### PR TITLE
sqlalchemy support

### PR DESCRIPTION
**Pull request by dwa**
This is cleaned up code developed at tobii.com (in collaboration with
knowit.se), which we use to connect from Superset (http://airbnb.io/superset/,
https://github.com/airbnb/superset/pull/2531) to an Athena DB.

Usage:
athena://<user>:<password>@athena.us-east-1.amazonaws.com/?region_name=<region>&s3_staging_dir=s3%3A//<staging_bucket_of_choice>

### CODE REVIEW

**Comment by dwa** [comment]
Forgot to mention:
- That it is based on https://github.com/dropbox/PyHive/blob/master/pyhive/sqlalchemy_presto.py
- With some changes and inspiration has been taken from https://github.com/cloudera/impyla/blob/master/impala/sqlalchemy.py

**Comment by laughingman7743** [comment]
Thanks PR!

I would like to write a test. PyAthenaJDBC test uses pytest.
I think that the following PyHive test will be helpful.

https://github.com/dropbox/PyHive/blob/master/pyhive/tests/sqlalchemy_test_case.py
https://github.com/dropbox/PyHive/blob/master/pyhive/tests/test_sqlalchemy_presto.py

The PyAthenaJDBC test also refers to PyHive's test.
Thanks,

**Comment by dwa** [comment]
Given the work on #14, are you still interested in this? Shall I work on some tests for this?

**Comment by laughingman7743** [comment]
Sorry, you do not need to write a test.
If you are interested in my implementation supporting SQLAlchemy, please connect to Superset with the following pull request branch. 

laughingman7743/PyAthenaJDBC#14

I do not use Superset, so I do not know if I can connect to Superset with my current implementation.
The connection string of SQLAlchemy is as follows. (Do not forget to quote access_key, secret_key and s3_staging_dir)

```
awsathena+jdbc://{access_key}:{secret_key}@athena.{region_name}.amazonaws.com:443/{schema_name}?s3_staging_dir={s3_staging_dir}&driver_path={driver_path}&...
```

Thanks,

**Pull request closed without merging**
